/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButtonGroup: typeof import('./src/components/My/ActionButtonGroup.vue')['default']
    ButtonContainer: typeof import('./src/components/Community/ButtonContainer.vue')['default']
    CardItem: typeof import('./src/components/Community/CardItem.vue')['default']
    Diary: typeof import('./src/components/My/diary.vue')['default']
    DiaryCard: typeof import('./src/components/My/DiaryCard.vue')['default']
    DiaryItem: typeof import('./src/components/My/DiaryItem.vue')['default']
    FoodCard: typeof import('./src/components/Community/FoodCard.vue')['default']
    Index: typeof import('./src/components/Food/Index.vue')['default']
    MapContainer: typeof import('./src/components/Map/MapContainer.vue')['default']
    PreferenceSelector: typeof import('./src/components/Food/PreferenceSelector.vue')['default']
    ProfileHeader: typeof import('./src/components/My/ProfileHeader.vue')['default']
    Result: typeof import('./src/components/Food/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchContainer: typeof import('./src/components/Community/SearchContainer.vue')['default']
    ServiceMenu: typeof import('./src/components/My/ServiceMenu.vue')['default']
    UploadPage: typeof import('./src/components/Community/UploadPage.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPagination: typeof import('vant/es')['Pagination']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRate: typeof import('vant/es')['Rate']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSkeletonImage: typeof import('vant/es')['SkeletonImage']
    VanSkeletonParagraph: typeof import('vant/es')['SkeletonParagraph']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    Verification: typeof import('./src/components/common/Verification.vue')['default']
  }
}
